/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MetaCryslIdeModule /* implements AbstractMetaCryslIdeModule  */{
}
