/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MetaCryslIdeSetup /* implements MetaCryslStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nMetaCryslRuntimeModule cannot be resolved."
      + "\nType mismatch: cannot convert from MetaCryslIdeModule to Module");
  }
}
