/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.tests.MetaCryslInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(MetaCryslInjectorProvider.class)
@SuppressWarnings("all")
public class MetaCryslParsingTest {
  @Inject
  private /* ParseHelper<MetaCrysl> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field MetaCryslParsingTest.parseHelper refers to the missing type MetaCrysl"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
