/**
 * generated by Xtext 2.20.0
 */
package de.darmstadt.tu.crossing.cryptSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.AddConstraints#getAddConstraints <em>Add Constraints</em>}</li>
 * </ul>
 *
 * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getAddConstraints()
 * @model
 * @generated
 */
public interface AddConstraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Add Constraints</b></em>' containment reference list.
   * The list contents are of type {@link de.darmstadt.tu.crossing.cryptSL.AddConstraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Constraints</em>' containment reference list.
   * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getAddConstraints_AddConstraints()
   * @model containment="true"
   * @generated
   */
  EList<AddConstraint> getAddConstraints();

} // AddConstraints
