/**
 * generated by Xtext 2.18.0
 */
package de.darmstadt.tu.crossing.cryptSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jvm Wildcard Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getJvmWildcardTypeReference()
 * @model
 * @generated
 */
public interface JvmWildcardTypeReference extends JvmWildcardTypeRef
{
} // JvmWildcardTypeReference
