/**
 * generated by Xtext 2.18.0
 */
package de.darmstadt.tu.crossing.cryptSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Jvm Wildcard Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getJvmWildcardTypeRef()
 * @model
 * @generated
 */
public interface JvmWildcardTypeRef extends EObject
{
} // JvmWildcardTypeRef
