/**
 * generated by Xtext 2.20.0
 */
package de.darmstadt.tu.crossing.cryptSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Refinement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.Refinement#getRefinementId <em>Refinement Id</em>}</li>
 *   <li>{@link de.darmstadt.tu.crossing.cryptSL.Refinement#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getRefinement()
 * @model
 * @generated
 */
public interface Refinement extends Domainmodel
{
  /**
   * Returns the value of the '<em><b>Refinement Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refinement Id</em>' attribute.
   * @see #setRefinementId(String)
   * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getRefinement_RefinementId()
   * @model
   * @generated
   */
  String getRefinementId();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.cryptSL.Refinement#getRefinementId <em>Refinement Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Refinement Id</em>' attribute.
   * @see #getRefinementId()
   * @generated
   */
  void setRefinementId(String value);

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference.
   * @see #setOperations(Operations)
   * @see de.darmstadt.tu.crossing.cryptSL.CryptSLPackage#getRefinement_Operations()
   * @model containment="true"
   * @generated
   */
  Operations getOperations();

  /**
   * Sets the value of the '{@link de.darmstadt.tu.crossing.cryptSL.Refinement#getOperations <em>Operations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operations</em>' containment reference.
   * @see #getOperations()
   * @generated
   */
  void setOperations(Operations value);

} // Refinement
