/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.metacrysl.ui.internal.MetacryslActivator;

public class MetaCryslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MetacryslActivator.getInstance().getInjector("org.xtext.example.mydsl.MetaCrysl");
	}

}
