/**
 * generated by Xtext 2.20.0
 */
package de.darmstadt.tu.crossing.cryptSL.impl;

import de.darmstadt.tu.crossing.cryptSL.CryptSLPackage;
import de.darmstadt.tu.crossing.cryptSL.JvmWildcardTypeReference;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Jvm Wildcard Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JvmWildcardTypeReferenceImpl extends JvmWildcardTypeRefImpl implements JvmWildcardTypeReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JvmWildcardTypeReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CryptSLPackage.Literals.JVM_WILDCARD_TYPE_REFERENCE;
  }

} //JvmWildcardTypeReferenceImpl
